#!/usr/bin/env bash
#
# fetch_data.sh — download Jeff Sackmann's tennis CSV datasets into data/raw/.
#
# Source repositories (public, on GitHub):
#   - https://github.com/JeffSackmann/tennis_atp   (ATP tour matches, players, rankings)
#   - https://github.com/JeffSackmann/tennis_wta   (WTA tour matches, players, rankings)
#
# These CSVs are the raw input for the Phase 1 pipeline. They live under
# data/raw/, which is git-ignored — we never commit upstream data, only the
# built Parquet artifact under data/built/.
#
# After fetching, this script records exactly what was pulled (source, time,
# and upstream commit hash) into data_manifest.txt for reproducibility.
#
# Usage:
#   ./fetch_data.sh
#
set -euo pipefail

# Resolve repo root so the script works regardless of where it's invoked from.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RAW_DIR="$ROOT/data/raw"
MANIFEST="$ROOT/data_manifest.txt"

mkdir -p "$RAW_DIR"

# Upstream repositories to fetch. Edit this list to add/remove sources.
REPOS=(
  "https://github.com/JeffSackmann/tennis_atp.git"
  "https://github.com/JeffSackmann/tennis_wta.git"
)

# Start a fresh manifest header for this run.
{
  echo "# data_manifest.txt"
  echo "# Generated by fetch_data.sh"
  echo "# Fetched at: $(date -u +"%Y-%m-%dT%H:%M:%SZ") (UTC)"
  echo "#"
} > "$MANIFEST"

for repo_url in "${REPOS[@]}"; do
  name="$(basename "$repo_url" .git)"
  dest="$RAW_DIR/$name"

  echo ">> Fetching $name ..."
  if [ -d "$dest/.git" ]; then
    # Already cloned — update to the latest commit on the default branch.
    git -C "$dest" pull --ff-only
  else
    # Shallow clone keeps the download small; we only need the working tree.
    git clone --depth 1 "$repo_url" "$dest"
  fi

  commit_hash="$(git -C "$dest" rev-parse HEAD)"
  csv_count="$(find "$dest" -maxdepth 1 -name '*.csv' | wc -l | tr -d ' ')"

  {
    echo "source:      $repo_url"
    echo "local_path:  data/raw/$name"
    echo "commit:      $commit_hash"
    echo "csv_files:   $csv_count"
    echo ""
  } >> "$MANIFEST"

  echo ">> $name done ($csv_count CSVs, commit ${commit_hash:0:12})"
done

echo ">> All sources fetched. Manifest written to data_manifest.txt"
